import type { ColumnConfig } from './tableConfig';

export const DEFAULT_COLUMNS: Record<string, ColumnConfig[]> = {
  courses: [
    { columnKey: 'id', label: 'ID', visible: true, order: 1 },
    { columnKey: 'title', label: '코스명', visible: true, order: 2 },
    { columnKey: 'description', label: '설명', visible: true, order: 3 },
    { columnKey: 'durationHours', label: '시간', visible: true, order: 4 },
    { columnKey: 'isOnline', label: '온라인', visible: true, order: 5 },
    { columnKey: 'goal', label: '교육 목표', visible: true, order: 6 },
    { columnKey: 'content', label: '교육 내용', visible: true, order: 7 },
    { columnKey: 'notes', label: '비고', visible: true, order: 8 },
    { columnKey: 'createdBy', label: '등록자', visible: true, order: 9 },
    { columnKey: 'createdAt', label: '등록일', visible: true, order: 10 },
    { columnKey: 'updatedAt', label: '수정일', visible: true, order: 11 },
    { columnKey: 'actions', label: '액션', visible: true, order: 99, fixed: 'right' },
  ],
  instructors: [
    { columnKey: 'id', label: 'ID', visible: true, order: 1 },
    { columnKey: 'userId', label: '사용자 ID', visible: true, order: 2 },
    { columnKey: 'name', label: '이름', visible: true, order: 3 },
    { columnKey: 'title', label: '직함', visible: true, order: 4 },
    { columnKey: 'email', label: '이메일', visible: true, order: 5 },
    { columnKey: 'phone', label: '전화번호', visible: true, order: 6 },
    { columnKey: 'affiliation', label: '소속', visible: true, order: 7 },
    { columnKey: 'specialties', label: '전문분야', visible: true, order: 8 },
    { columnKey: 'degrees', label: '학위', visible: true, order: 9 },
    { columnKey: 'careers', label: '주요경력', visible: true, order: 10 },
    { columnKey: 'publications', label: '출판/논문', visible: true, order: 11 },
    { columnKey: 'certifications', label: '자격증', visible: true, order: 12 },
    { columnKey: 'awards', label: '수상', visible: true, order: 13 },
    { columnKey: 'avatarUrl', label: '프로필 이미지', visible: true, order: 14 },
    { columnKey: 'tagline', label: '한줄 소개', visible: true, order: 15 },
    { columnKey: 'bio', label: '자기소개', visible: true, order: 16 },
    { columnKey: 'createdBy', label: '등록자', visible: true, order: 17 },
    { columnKey: 'createdAt', label: '등록일', visible: true, order: 18 },
    { columnKey: 'updatedAt', label: '수정일', visible: true, order: 19 },
    { columnKey: 'actions', label: '액션', visible: true, order: 99, fixed: 'right' },
  ],
  templates: [
    { columnKey: 'id', label: 'ID', visible: true, order: 1 },
    { columnKey: 'name', label: '템플릿명', visible: true, order: 2 },
    { columnKey: 'type', label: '타입', visible: true, order: 3 },
    { columnKey: 'createdBy', label: '등록자', visible: true, order: 4 },
    { columnKey: 'createdAt', label: '등록일', visible: true, order: 5 },
    { columnKey: 'updatedAt', label: '수정일', visible: true, order: 6 },
    { columnKey: 'actions', label: '액션', visible: true, order: 99, fixed: 'right' },
  ],
  users: [
    { columnKey: 'id', label: 'ID', visible: true, order: 1 },
    { columnKey: 'email', label: '이메일', visible: true, order: 2 },
    { columnKey: 'name', label: '이름', visible: true, order: 3 },
    { columnKey: 'role', label: '권한', visible: true, order: 4 },
    { columnKey: 'isActive', label: '활성', visible: true, order: 5 },
    { columnKey: 'provider', label: '가입 경로', visible: true, order: 6 },
    { columnKey: 'createdAt', label: '가입일', visible: true, order: 7 },
    { columnKey: 'lastLoginAt', label: '마지막 로그인', visible: true, order: 8 },
    { columnKey: 'actions', label: '액션', visible: true, order: 99, fixed: 'right' },
  ],
  schedules: [
    { columnKey: 'id', label: 'ID', visible: true, order: 1 },
    { columnKey: 'courseId', label: '코스 ID', visible: true, order: 2 },
    { columnKey: 'instructorId', label: '강사 ID', visible: true, order: 3 },
    { columnKey: 'date', label: '일정', visible: true, order: 4 },
    { columnKey: 'location', label: '장소', visible: true, order: 5 },
    { columnKey: 'audience', label: '대상', visible: true, order: 6 },
    { columnKey: 'remarks', label: '비고', visible: true, order: 7 },
    { columnKey: 'createdBy', label: '등록자', visible: true, order: 8 },
    { columnKey: 'createdAt', label: '등록일', visible: true, order: 9 },
    { columnKey: 'actions', label: '액션', visible: true, order: 99, fixed: 'right' },
  ],
  lectures: [
    { columnKey: 'id', label: 'ID', visible: true, order: 1 },
    { columnKey: 'courseId', label: '코스 ID', visible: true, order: 2 },
    { columnKey: 'title', label: '강의명', visible: true, order: 3 },
    { columnKey: 'description', label: '설명', visible: true, order: 4 },
    { columnKey: 'hours', label: '시간', visible: true, order: 5 },
    { columnKey: 'order', label: '순서', visible: true, order: 6 },
    { columnKey: 'createdBy', label: '등록자', visible: true, order: 7 },
    { columnKey: 'createdAt', label: '등록일', visible: true, order: 8 },
    { columnKey: 'updatedAt', label: '수정일', visible: true, order: 9 },
    { columnKey: 'actions', label: '액션', visible: true, order: 99, fixed: 'right' },
  ],
};
